[versions]
androidx-core = "1.12.0"
androidx-appcompat = "1.6.1"
androidx-activity = "1.8.0"
androidx-constraintlayout = "2.1.4"
material = "1.10.0"
junit = "4.13.2"
androidx-junit = "1.1.5"
espresso-core = "3.5.1"

[plugins]
android-application = { id = "com.android.application", version = "8.2.0" }

[libraries]
core = { group = "androidx.core", name = "core-ktx", version.ref = "androidx-core" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidx-appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
activity = { group = "androidx.activity", name = "activity", version.ref = "androidx-activity" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidx-constraintlayout" }

# Test libs
junit = { group = "junit", name = "junit", version.ref = "junit" }
ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidx-junit" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espresso-core" }

